export const data = {
  UserID: "71c5y0imHVRcO9gbJBJtavRIOVh2",
  Volunteer_Name: "Mayank",
  Volunteer_Address: "Add",
  Volunteer_College: "PESU",
  Volunteer_Organization: "DeloitteIND",
  Volunteer_Academic_Qualifications: "btech",
  Volunteer_Occupation: "student",
  Volunteer_email: "mayank1403@gmail.com",
  Volunteer_Nationality: "indian",
  Volunteer_Preferred_Mode: ["Offline"],
  Volunteer_Number: 9999999999,
  Volunteer_Number_Of_Activities_Attended: 0,
  Volunteer_Number_Of_Activities_Opted_Out: 0,
  Volunteer_Preferred_Locations: [
    "Central Zone",
    "Navi Mumbai",
    "Outside Mumbai",
  ],
  Volunteer_Availability: ["Weekdays", "Weekends"],
  Volunteer_Interested_Activity_Type: [],
  Volunteer_Languages: ["Hindi", "English"],
  Volunteer_Skills: ["Story Telling", "Photography"],
};
