const mongoose = require('mongoose');
//ActivityType,Date,Time,Duration
const ActivitySchema = new mongoose.Schema({
    ActivityName:{
        type:String,
        require:true,
        default:""
    },
    ActivityType:{
        type:Array,
        require:true,
        default:[]
    },
    ActivityDate:{
        type:String,
        require:true,
    },
    ActivityTime:{
        type:String,
        require:true,
        default:""
    },
    ActivityDurationInMinutes:{
        type:Number,
        require:true,
        default:""
    },
    Activity_Location:{
        type:Array,
        default:[]
    },
    Activity_Mode:{
        type:String,
        default:""
    },
    Language_Preference:{
        type:Array,
        default:[]
    },
    Activity_availability:{
        type:Array,
        default:[]
    },
    Preferred_skills:{
        type:Array,
        default:[]
    },
    Current_assigned:{
        type:Number,
        default:0
    },
    Max_volunteers:{
        type:Number,
        default:5
    },
    Activity_Address:{
        type:String,
        default:''
    },
    Activity_Description:{
        type:String,
        default:''
    },

    Activity_Attendance:{
        type:Array,
        default:[]
    },
    AssignedTo:{
        type:Array,
        default:[]
    }
},{timestamps:true}
)

module.exports = mongoose.model("Activity",ActivitySchema);